import type { FarmRecord, WasteCollectionLog, DashboardMetrics } from './types';

export const mockFarmRecord: FarmRecord = {
  id: 'ZC-2026-0042',
  batchCode: 'ZC-BATCH-042-2026',
  farmerName: 'Grace Wanjiku Kamau',
  farmLocation: 'Kangai, Mwea Irrigation Scheme',
  ward: 'Mwea',
  cropType: 'Tomatoes (Roma Variety)',
  lastSprayDate: '2026-04-12',
  chemical: 'Chlorpyrifos (Organophosphate)',
  preHarvestIntervalDays: 14,
  safeHarvestDate: '2026-04-26',
  harvestDate: '2026-04-27',
  certifiedAt: '2026-04-27T08:32:00Z',
  status: 'safe',
};

export const mockFarmRecords: FarmRecord[] = [
  mockFarmRecord,
  {
    id: 'ZC-2026-0043',
    batchCode: 'ZC-BATCH-043-2026',
    farmerName: 'Peter Njoroge Waweru',
    farmLocation: 'Gichugu Hills, Ngariama Village',
    ward: 'Gichugu',
    cropType: 'French Beans',
    lastSprayDate: '2026-05-05',
    chemical: 'Dimethoate (Organophosphate)',
    preHarvestIntervalDays: 7,
    safeHarvestDate: '2026-05-12',
    harvestDate: '2026-05-13',
    certifiedAt: '2026-05-13T10:15:00Z',
    status: 'safe',
  },
  {
    id: 'ZC-2026-0044',
    batchCode: 'ZC-BATCH-044-2026',
    farmerName: 'Mary Njeri Muthoni',
    farmLocation: 'Kagio Market Area, Kirinyaga Central',
    ward: 'Kirinyaga Central',
    cropType: 'Tomatoes (Beef Variety)',
    lastSprayDate: '2026-05-12',
    chemical: 'Mancozeb (Fungicide)',
    preHarvestIntervalDays: 7,
    safeHarvestDate: '2026-05-19',
    harvestDate: '2026-05-20',
    certifiedAt: '',
    status: 'pending',
  },
  {
    id: 'ZC-2026-0045',
    batchCode: 'ZC-BATCH-045-2026',
    farmerName: 'John Kamau Njenga',
    farmLocation: 'Ndia Sub-County, Kiamutuga',
    ward: 'Ndia',
    cropType: 'Tomatoes (Roma Variety)',
    lastSprayDate: '2026-04-30',
    chemical: 'Cypermethrin (Pyrethroid)',
    preHarvestIntervalDays: 3,
    safeHarvestDate: '2026-05-03',
    harvestDate: '2026-05-04',
    certifiedAt: '2026-05-04T14:00:00Z',
    status: 'safe',
  },
  {
    id: 'ZC-2026-0046',
    batchCode: 'ZC-BATCH-046-2026',
    farmerName: 'Esther Wairimu Gathuku',
    farmLocation: 'Kanyekiine, Mwea East Ward',
    ward: 'Mwea',
    cropType: 'French Beans',
    lastSprayDate: '2026-05-01',
    chemical: 'Profenofos (Organophosphate)',
    preHarvestIntervalDays: 14,
    safeHarvestDate: '2026-05-15',
    harvestDate: '2026-05-15',
    certifiedAt: '2026-05-15T09:00:00Z',
    status: 'safe',
  },
  {
    id: 'ZC-2026-0047',
    batchCode: 'ZC-BATCH-047-2026',
    farmerName: 'Samuel Githinji Kiragu',
    farmLocation: 'Mutithi Village, Mwea West',
    ward: 'Mwea',
    cropType: 'Rice (Basmati Variety)',
    lastSprayDate: '2026-04-20',
    chemical: 'Lambda-cyhalothrin (Pyrethroid)',
    preHarvestIntervalDays: 7,
    safeHarvestDate: '2026-04-27',
    harvestDate: '2026-04-28',
    certifiedAt: '2026-04-28T11:45:00Z',
    status: 'safe',
  },
  {
    id: 'ZC-2026-0048',
    batchCode: 'ZC-BATCH-048-2026',
    farmerName: 'Joseph Githinji Mwangi',
    farmLocation: 'Baragwi, Kirinyaga Central',
    ward: 'Kirinyaga Central',
    cropType: 'Tomatoes (Cocktail Variety)',
    lastSprayDate: '2026-05-08',
    chemical: 'Imidacloprid (Neonicotinoid)',
    preHarvestIntervalDays: 3,
    safeHarvestDate: '2026-05-11',
    harvestDate: '2026-05-12',
    certifiedAt: '2026-05-12T16:20:00Z',
    status: 'safe',
  },
];

export const mockMetrics: DashboardMetrics = {
  activeFarmers: 248,
  biomassCollectedKg: 18420,
  ecoBriquettesProduced: 3684,
  totalMpesaPayoutsKES: 184200,
};

export const mockWasteLogs: WasteCollectionLog[] = [
  {
    id: 'WCL-001',
    farmerName: 'Grace Wanjiku Kamau',
    ward: 'Mwea',
    wasteType: 'Rice Husks',
    weightKg: 85,
    collectionDate: '2026-04-28',
    riderName: 'James Mwangi',
    mpesaAmountKES: 425,
    status: 'completed',
  },
  {
    id: 'WCL-002',
    farmerName: 'Peter Njoroge Waweru',
    ward: 'Gichugu',
    wasteType: 'Coffee Pulp',
    weightKg: 120,
    collectionDate: '2026-04-27',
    riderName: 'Samuel Kariuki',
    mpesaAmountKES: 600,
    status: 'completed',
  },
  {
    id: 'WCL-003',
    farmerName: 'Mary Njeri Muthoni',
    ward: 'Ndia',
    wasteType: 'Tomato Stalks',
    weightKg: 60,
    collectionDate: '2026-04-27',
    riderName: 'James Mwangi',
    mpesaAmountKES: 300,
    status: 'in-transit',
  },
  {
    id: 'WCL-004',
    farmerName: 'John Kamau Njenga',
    ward: 'Kirinyaga Central',
    wasteType: 'Rice Husks',
    weightKg: 200,
    collectionDate: '2026-04-26',
    riderName: 'David Gitau',
    mpesaAmountKES: 1000,
    status: 'completed',
  },
  {
    id: 'WCL-005',
    farmerName: 'Esther Wairimu Gathuku',
    ward: 'Mwea',
    wasteType: 'French Bean Stalks',
    weightKg: 45,
    collectionDate: '2026-04-26',
    riderName: 'Samuel Kariuki',
    mpesaAmountKES: 225,
    status: 'pending',
  },
  {
    id: 'WCL-006',
    farmerName: 'Joseph Githinji Mwangi',
    ward: 'Gichugu',
    wasteType: 'Coffee Pulp',
    weightKg: 95,
    collectionDate: '2026-04-25',
    riderName: 'David Gitau',
    mpesaAmountKES: 475,
    status: 'completed',
  },
];
