import type { RiderProfile, RiderPickupTask, RiderEarningsSummary } from './types';

export const mockRider: RiderProfile = {
  id: 'R-007',
  name: 'James Mwangi',
  phone: '+254 723 456 789',
  ward: 'Mwea',
  vehicleType: 'Motorcycle (Bodaboda)',
  joinedDate: '2026-02-01',
};

export const mockRiderPickups: RiderPickupTask[] = [
  {
    id: 'PKP-T01',
    farmerName: 'Grace Wanjiku Kamau',
    farmerPhone: '+254 712 345 678',
    farmLocation: 'Kangai sub-location, Mwea',
    ward: 'Mwea',
    wasteType: 'Rice Husks',
    estimatedWeightKg: 85,
    scheduledTime: '09:00',
    scheduledDate: '2026-05-11',
    distanceKm: 2.4,
    status: 'assigned',
    payoutRateKES: 5,
    notes: 'Farm is behind the main irrigation canal. Gate on the left — call ahead.',
  },
  {
    id: 'PKP-T02',
    farmerName: 'Peter Njoroge Waweru',
    farmerPhone: '+254 734 567 890',
    farmLocation: 'Kanyekiine, Mwea',
    ward: 'Mwea',
    wasteType: 'Tomato Stalks',
    estimatedWeightKg: 45,
    scheduledTime: '11:00',
    scheduledDate: '2026-05-11',
    distanceKm: 4.1,
    status: 'pending',
    payoutRateKES: 5,
  },
  {
    id: 'PKP-T03',
    farmerName: 'Esther Wairimu Gathuku',
    farmerPhone: '+254 745 678 901',
    farmLocation: 'Nyangati, Mwea',
    ward: 'Mwea',
    wasteType: 'French Bean Stalks',
    estimatedWeightKg: 60,
    scheduledTime: '14:00',
    scheduledDate: '2026-05-11',
    distanceKm: 6.8,
    status: 'pending',
    payoutRateKES: 5,
  },
  {
    id: 'PKP-T04',
    farmerName: 'John Kamau Njenga',
    farmerPhone: '+254 756 789 012',
    farmLocation: 'Mwea Irrigation Block 7',
    ward: 'Mwea',
    wasteType: 'Rice Husks',
    estimatedWeightKg: 120,
    scheduledTime: '08:00',
    scheduledDate: '2026-05-11',
    distanceKm: 1.2,
    status: 'collected',
    actualWeightKg: 118,
    actualPayoutKES: 590,
    payoutRateKES: 5,
    collectedAt: '2026-05-11T08:45:00Z',
    mpesaTransactionId: 'QRT5Y8W2X1',
  },
];

export const mockRiderEarnings: RiderEarningsSummary = {
  todayKES: 590,
  thisWeekKES: 2340,
  thisMonthKES: 8750,
  totalKES: 24500,
  completedPickups: 89,
  totalWeightKg: 4480,
  dailyEarnings: [
    { day: 'Mon', amountKES: 450 },
    { day: 'Tue', amountKES: 750 },
    { day: 'Wed', amountKES: 300 },
    { day: 'Thu', amountKES: 840 },
    { day: 'Fri', amountKES: 590 },
    { day: 'Sat', amountKES: 0 },
    { day: 'Sun', amountKES: 0 },
  ],
};
