import type { FarmRecord, WasteCollectionLog, DashboardMetrics } from './types';

export const mockFarmRecord: FarmRecord = {
  id: 'ZC-2026-0042',
  batchCode: 'ZC-BATCH-042-2026',
  farmerName: 'Grace Wanjiku Kamau',
  farmLocation: 'Kangai, Mwea Irrigation Scheme',
  ward: 'Mwea',
  cropType: 'Tomatoes (Roma Variety)',
  lastSprayDate: '2026-04-12',
  chemical: 'Chlorpyrifos (Organophosphate)',
  preHarvestIntervalDays: 14,
  safeHarvestDate: '2026-04-26',
  harvestDate: '2026-04-27',
  certifiedAt: '2026-04-27T08:32:00Z',
  status: 'safe',
};

export const mockMetrics: DashboardMetrics = {
  activeFarmers: 248,
  biomassCollectedKg: 18420,
  ecoBriquettesProduced: 3684,
  totalMpesaPayoutsKES: 184200,
};

export const mockWasteLogs: WasteCollectionLog[] = [
  {
    id: 'WCL-001',
    farmerName: 'Grace Wanjiku Kamau',
    ward: 'Mwea',
    wasteType: 'Rice Husks',
    weightKg: 85,
    collectionDate: '2026-04-28',
    riderName: 'James Mwangi',
    mpesaAmountKES: 425,
    status: 'completed',
  },
  {
    id: 'WCL-002',
    farmerName: 'Peter Njoroge Waweru',
    ward: 'Gichugu',
    wasteType: 'Coffee Pulp',
    weightKg: 120,
    collectionDate: '2026-04-27',
    riderName: 'Samuel Kariuki',
    mpesaAmountKES: 600,
    status: 'completed',
  },
  {
    id: 'WCL-003',
    farmerName: 'Mary Njeri Muthoni',
    ward: 'Ndia',
    wasteType: 'Tomato Stalks',
    weightKg: 60,
    collectionDate: '2026-04-27',
    riderName: 'James Mwangi',
    mpesaAmountKES: 300,
    status: 'in-transit',
  },
  {
    id: 'WCL-004',
    farmerName: 'John Kamau Njenga',
    ward: 'Kirinyaga Central',
    wasteType: 'Rice Husks',
    weightKg: 200,
    collectionDate: '2026-04-26',
    riderName: 'David Gitau',
    mpesaAmountKES: 1000,
    status: 'completed',
  },
  {
    id: 'WCL-005',
    farmerName: 'Esther Wairimu Gathuku',
    ward: 'Mwea',
    wasteType: 'French Bean Stalks',
    weightKg: 45,
    collectionDate: '2026-04-26',
    riderName: 'Samuel Kariuki',
    mpesaAmountKES: 225,
    status: 'pending',
  },
  {
    id: 'WCL-006',
    farmerName: 'Joseph Githinji Mwangi',
    ward: 'Gichugu',
    wasteType: 'Coffee Pulp',
    weightKg: 95,
    collectionDate: '2026-04-25',
    riderName: 'David Gitau',
    mpesaAmountKES: 475,
    status: 'completed',
  },
];
